In [1]:
import numpy as np

In [2]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [4]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [6]:
np.arange(3,22,3)

array([ 3,  6,  9, 12, 15, 18, 21])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.linspace(0,2,5) # divides the number in range 0 & 2 including 2 in 5 intervals

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [15]:
np.random.rand(3,5)

array([[0.10716559, 0.30809596, 0.45163955, 0.92565834, 0.95180794],
       [0.43677953, 0.91815394, 0.85026864, 0.13563015, 0.76999359],
       [0.30085634, 0.63205553, 0.1713369 , 0.63227532, 0.08794005]])

In [16]:
np.random.rand(9,5)

array([[0.70624391, 0.63284697, 0.65565461, 0.39446702, 0.02611798],
       [0.38958525, 0.63079203, 0.13474151, 0.59574268, 0.04842488],
       [0.24445306, 0.93101168, 0.16863523, 0.02137634, 0.53925941],
       [0.59849804, 0.89390402, 0.24242258, 0.65427034, 0.05040243],
       [0.06135024, 0.58641608, 0.88806375, 0.74157821, 0.90084356],
       [0.77000036, 0.87702709, 0.11976166, 0.5016551 , 0.05865376],
       [0.22611392, 0.52373973, 0.89081831, 0.29535767, 0.46048617],
       [0.90594177, 0.21110072, 0.46083134, 0.50870186, 0.09578325],
       [0.73811405, 0.01996614, 0.1116282 , 0.30108783, 0.20638259]])

In [27]:
np.random.randn(3,5)

array([[-0.26210689, -0.49572721, -1.06962816,  0.52129658,  0.08799762],
       [-0.94930797,  1.23576965,  0.22112296, -0.04490648, -0.47869814],
       [ 0.81108044,  0.59116735, -0.01619262, -1.36844469, -1.3997595 ]])

In [32]:
np.random.randint(0,50,20)

array([43, 16, 45, 24, 29,  4, 37, 24, 37, 34, 30, 36,  5, 38, 41, 41, 42,
       38, 35, 28])

In [33]:
sample_array=np.arange(0,30)

In [35]:
print(sample_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [42]:
sample_array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [44]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
mat[1,2]

6

In [48]:
mat[2,2]

9

In [49]:
mat[2,:]

array([7, 8, 9])

In [52]:
mat[:,(1,2)]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [54]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
sample_array=sample_array.reshape(5,6)

In [57]:
sample_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [58]:
mat+mat

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [60]:
np.max(sample_array)

29

In [61]:
np.min(sample_array)

0

In [62]:
np.sqrt(sample_array)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563],
       [4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242, 5.29150262,
        5.38516481]])

In [64]:
np.log(sample_array)

C:\Users\Allahbaksh Mulla\AppData\Local\Temp\ipykernel_8396\988743405.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(sample_array)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
        2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872,
        2.83321334],
       [2.89037176, 2.94443898, 2.99573227, 3.04452244, 3.09104245,
        3.13549422],
       [3.17805383, 3.21887582, 3.25809654, 3.29583687, 3.33220451,
        3.36729583]])

In [65]:
sample_array[0,0]=30

In [66]:
sample_array

array([[30,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [67]:
np.mean(sample_array)

15.5