In [38]:
import numpy as np

In [39]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
x=np.arange(15)

In [41]:
arr=np.zeros(10)
arr[5]=1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [42]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [43]:
arr[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [44]:
arr=np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
arr=np.random.rand(30)
np.mean(arr)

0.44130019039504453

In [ ]:
https://github.com/Premalatha-success/Datasets/blob/main/CardioGoodFitness-1.csv